# Generated by Django 5.1.2 on 2024-11-14 17:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=40)),
                ('effect', models.TextField()),
                ('attack', models.CharField(max_length=7, null=True)),
                ('defense', models.CharField(max_length=7, null=True)),
                ('level_rank', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('race', models.CharField(max_length=30, null=True)),
                ('attribute', models.CharField(max_length=10, null=True)),
                ('archetype', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=15)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='cards.card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='cards.set')),
            ],
            options={
                'unique_together': {('card', 'set', 'rarity')},
            },
        ),
    ]
