# Generated by Django 5.1.2 on 2024-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_set_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='rarity',
            field=models.CharField(max_length=100),
        ),
    ]
