# Generated by Django 5.1.2 on 2024-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='card_images/default.jpg', upload_to='card_images/'),
        ),
    ]
