# Generated by Django 5.1.2 on 2024-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='card_images/default.jpg', upload_to='card_images/'),
        ),
    ]
