# Generated by Django 5.1.2 on 2024-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='frame_type',
            field=models.CharField(default='monster', max_length=40),
        ),
    ]
