# Generated by Django 5.1.2 on 2024-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_rename_race_card_monster_race_card_spell_trap_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='defense',
            field=models.IntegerField(null=True),
        ),
    ]
