# Generated by Django 5.1.2 on 2024-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_attack_alter_card_defense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='archetype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
