# Generated by Django 5.1.2 on 2024-11-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_small_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='small_image',
        ),
    ]
