# Generated by Django 5.1.2 on 2024-12-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_remove_card_small_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardSet',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
